-- Fallback Android POS
--
-- A standalone point-of-sale register that staff run on Android tablets as a
-- PWA. It is the backup register used when the primary POS (PetPooja) is down
-- or the venue is offline. Orders captured here are stored in dedicated pos_*
-- tables and, via the pos_checkout function, flow into the existing CRM
-- (visits / order_items / timeline_entries) so a fallback sale still enriches
-- Customer360. All sync is idempotent on a device-generated client_order_id so
-- an offline queue can retry safely without creating duplicates.

create type public.pos_order_status as enum ('open', 'completed', 'voided');

create table if not exists public.pos_menu_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (name)
);

create table if not exists public.pos_menu_items (
  id uuid primary key default gen_random_uuid(),
  category_id uuid references public.pos_menu_categories(id) on delete set null,
  name text not null,
  sku text,
  price numeric(12,2) not null default 0,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pos_menu_items_category_idx
  on public.pos_menu_items(category_id, sort_order);

create table if not exists public.pos_orders (
  id uuid primary key default gen_random_uuid(),
  client_order_id uuid not null,
  order_number bigint generated by default as identity,
  person_id uuid references public.people(id) on delete set null,
  customer_name text,
  status public.pos_order_status not null default 'completed',
  subtotal numeric(12,2) not null default 0,
  tax_amount numeric(12,2) not null default 0,
  discount_amount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text,
  amount_tendered numeric(12,2),
  change_due numeric(12,2),
  notes text,
  source text not null default 'fallback_pos',
  outlet_id text,
  placed_at timestamptz not null default now(),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique (client_order_id)
);

create index if not exists pos_orders_placed_at_idx
  on public.pos_orders(placed_at desc);
create index if not exists pos_orders_person_idx
  on public.pos_orders(person_id);

create table if not exists public.pos_order_lines (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.pos_orders(id) on delete cascade,
  menu_item_id uuid references public.pos_menu_items(id) on delete set null,
  item_name text not null,
  category text,
  unit_price numeric(12,2) not null default 0,
  quantity numeric(10,2) not null default 1,
  line_total numeric(12,2) not null default 0,
  modifiers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pos_order_lines_order_idx
  on public.pos_order_lines(order_id);

create table if not exists public.pos_payments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.pos_orders(id) on delete cascade,
  method text not null default 'cash',
  amount numeric(12,2) not null default 0,
  amount_tendered numeric(12,2),
  change_due numeric(12,2),
  reference text,
  created_at timestamptz not null default now()
);

create index if not exists pos_payments_order_idx
  on public.pos_payments(order_id);

-- Row Level Security ---------------------------------------------------------
alter table public.pos_menu_categories enable row level security;
alter table public.pos_menu_items enable row level security;
alter table public.pos_orders enable row level security;
alter table public.pos_order_lines enable row level security;
alter table public.pos_payments enable row level security;

-- Menu is readable by any signed-in staff member and managed by managers.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['pos_menu_categories', 'pos_menu_items']
  loop
    execute format('drop policy if exists "staff read %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "staff read %s" on public.%I for select to authenticated using (public.current_app_role() in (''barista'', ''manager'', ''admin''))',
      table_name,
      table_name
    );
    execute format('drop policy if exists "managers manage %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "managers manage %s" on public.%I for all to authenticated using (public.current_app_role() in (''manager'', ''admin'')) with check (public.current_app_role() in (''manager'', ''admin''))',
      table_name,
      table_name
    );
  end loop;
end $$;

-- Sales records are readable by any staff member. Baristas ring up sales
-- through the pos_checkout function (security definer), so direct table writes
-- stay restricted to managers.
do $$
declare
  table_name text;
begin
  foreach table_name in array array['pos_orders', 'pos_order_lines', 'pos_payments']
  loop
    execute format('drop policy if exists "staff read %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "staff read %s" on public.%I for select to authenticated using (public.current_app_role() in (''barista'', ''manager'', ''admin''))',
      table_name,
      table_name
    );
    execute format('drop policy if exists "managers manage %s" on public.%I', table_name, table_name);
    execute format(
      'create policy "managers manage %s" on public.%I for all to authenticated using (public.current_app_role() in (''manager'', ''admin'')) with check (public.current_app_role() in (''manager'', ''admin''))',
      table_name,
      table_name
    );
  end loop;
end $$;

-- Checkout ------------------------------------------------------------------
-- Atomically records a completed sale and mirrors it into the CRM. Idempotent
-- on client_order_id: replaying the same offline order returns the original
-- record instead of duplicating it.
create or replace function public.pos_checkout(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_client_order_id uuid;
  v_person_id uuid;
  v_order_id uuid;
  v_order_number bigint;
  v_created boolean := false;
  v_placed_at timestamptz;
  v_subtotal numeric(12,2) := 0;
  v_tax numeric(12,2);
  v_discount numeric(12,2);
  v_total numeric(12,2);
  v_tendered numeric(12,2);
  v_change numeric(12,2);
  v_method text;
  v_line jsonb;
  v_visit_id uuid;
begin
  v_role := public.current_app_role();
  if v_role not in ('barista', 'manager', 'admin') then
    raise exception 'not authorized to record POS sales';
  end if;

  v_client_order_id := (payload->>'client_order_id')::uuid;
  if v_client_order_id is null then
    raise exception 'client_order_id is required';
  end if;

  -- Idempotency: if this device order was already recorded, return it as-is.
  select id, order_number into v_order_id, v_order_number
  from public.pos_orders
  where client_order_id = v_client_order_id;

  if v_order_id is not null then
    return jsonb_build_object(
      'order_id', v_order_id,
      'order_number', v_order_number,
      'created', false
    );
  end if;

  if jsonb_typeof(payload->'lines') is distinct from 'array'
     or jsonb_array_length(payload->'lines') = 0 then
    raise exception 'order must contain at least one line';
  end if;

  for v_line in select * from jsonb_array_elements(payload->'lines')
  loop
    v_subtotal := v_subtotal
      + round((v_line->>'unit_price')::numeric * (v_line->>'quantity')::numeric, 2);
  end loop;

  v_tax := coalesce((payload->>'tax_amount')::numeric, 0);
  v_discount := coalesce((payload->>'discount_amount')::numeric, 0);
  v_total := round(v_subtotal + v_tax - v_discount, 2);
  v_method := coalesce(nullif(payload->>'payment_method', ''), 'cash');
  v_tendered := nullif(payload->>'amount_tendered', '')::numeric;
  v_change := case
    when v_tendered is not null then greatest(round(v_tendered - v_total, 2), 0)
    else null
  end;
  v_placed_at := coalesce(nullif(payload->>'placed_at', '')::timestamptz, now());
  v_person_id := nullif(payload->>'person_id', '')::uuid;

  insert into public.pos_orders (
    client_order_id, person_id, customer_name, status, subtotal, tax_amount,
    discount_amount, total, payment_method, amount_tendered, change_due, notes,
    outlet_id, placed_at, created_by
  )
  values (
    v_client_order_id,
    v_person_id,
    nullif(payload->>'customer_name', ''),
    'completed',
    v_subtotal,
    v_tax,
    v_discount,
    v_total,
    v_method,
    v_tendered,
    v_change,
    nullif(payload->>'notes', ''),
    nullif(payload->>'outlet_id', ''),
    v_placed_at,
    auth.uid()
  )
  on conflict (client_order_id) do nothing
  returning id, order_number into v_order_id, v_order_number;

  if v_order_id is null then
    -- Lost a race with a concurrent replay of the same order; return the winner.
    select id, order_number into v_order_id, v_order_number
    from public.pos_orders
    where client_order_id = v_client_order_id;
    return jsonb_build_object(
      'order_id', v_order_id,
      'order_number', v_order_number,
      'created', false
    );
  end if;

  v_created := true;

  insert into public.pos_order_lines (
    order_id, menu_item_id, item_name, category, unit_price, quantity,
    line_total, modifiers
  )
  select
    v_order_id,
    nullif(line->>'menu_item_id', '')::uuid,
    line->>'item_name',
    nullif(line->>'category', ''),
    (line->>'unit_price')::numeric,
    (line->>'quantity')::numeric,
    round((line->>'unit_price')::numeric * (line->>'quantity')::numeric, 2),
    coalesce(line->'modifiers', '[]'::jsonb)
  from jsonb_array_elements(payload->'lines') as line;

  insert into public.pos_payments (
    order_id, method, amount, amount_tendered, change_due, reference
  )
  values (
    v_order_id,
    v_method,
    v_total,
    v_tendered,
    v_change,
    nullif(payload->>'payment_reference', '')
  );

  -- Mirror the sale into the CRM when it is tied to a known customer.
  if v_person_id is not null then
    insert into public.visits (
      person_id, outlet_id, visited_at, source, external_order_id,
      gross_amount, net_amount, payment_method, metadata
    )
    values (
      v_person_id,
      nullif(payload->>'outlet_id', ''),
      v_placed_at,
      'fallback_pos',
      v_client_order_id::text,
      v_total,
      v_total,
      v_method,
      jsonb_build_object('pos_order_id', v_order_id, 'order_number', v_order_number)
    )
    on conflict (source, external_order_id) do nothing
    returning id into v_visit_id;

    if v_visit_id is not null then
      insert into public.order_items (
        visit_id, external_item_id, item_name, category, quantity, unit_price,
        modifiers
      )
      select
        v_visit_id,
        nullif(line->>'menu_item_id', ''),
        line->>'item_name',
        nullif(line->>'category', ''),
        (line->>'quantity')::numeric,
        (line->>'unit_price')::numeric,
        coalesce(line->'modifiers', '[]'::jsonb)
      from jsonb_array_elements(payload->'lines') as line;

      insert into public.timeline_entries (
        person_id, event_type, title, summary, occurred_at, source_type,
        source_id, visibility, metadata, created_by
      )
      values (
        v_person_id,
        'pos_sale',
        'Fallback POS sale',
        format('Order #%s · %s', v_order_number, to_char(v_total, 'FM999999990.00')),
        v_placed_at,
        'fallback_pos',
        v_order_id,
        'barista',
        jsonb_build_object('order_number', v_order_number, 'total', v_total),
        auth.uid()
      )
      on conflict (source_type, source_id, event_type) do nothing;
    end if;
  end if;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number,
    'created', v_created,
    'total', v_total,
    'change_due', v_change
  );
end;
$$;

revoke all on function public.pos_checkout(jsonb) from public;
grant execute on function public.pos_checkout(jsonb) to authenticated;

-- updated_at maintenance -----------------------------------------------------
drop trigger if exists pos_menu_categories_updated_at on public.pos_menu_categories;
create trigger pos_menu_categories_updated_at
before update on public.pos_menu_categories
for each row execute function public.sync_updated_at();

drop trigger if exists pos_menu_items_updated_at on public.pos_menu_items;
create trigger pos_menu_items_updated_at
before update on public.pos_menu_items
for each row execute function public.sync_updated_at();

-- Default fallback menu ------------------------------------------------------
-- The 11th Bean menu so the register is usable the moment it is opened.
-- Managers can edit these later; re-running the migration will not duplicate.
insert into public.pos_menu_categories (name, sort_order)
values
  ('Bakes', 1),
  ('Savoury', 2)
on conflict (name) do nothing;

insert into public.pos_menu_items (category_id, name, sku, price, sort_order)
select c.id, v.name, v.sku, v.price, v.sort_order
from (values
  ('Bakes', 'Brownie', 'BRW', 100.00, 1),
  ('Bakes', 'Cake Pop', 'CKP', 60.00, 2),
  ('Bakes', 'Lemon Blueberry Cake', 'LBC', 90.00, 3),
  ('Bakes', 'Cookie', 'CKE', 70.00, 4),
  ('Bakes', 'Cupcake', 'CUP', 60.00, 5),
  ('Savoury', 'Roll', 'ROL', 90.00, 1),
  ('Savoury', 'Pizza Pocket', 'PZP', 90.00, 2)
) as v(category, name, sku, price, sort_order)
join public.pos_menu_categories c on c.name = v.category
where not exists (
  select 1 from public.pos_menu_items m where m.sku = v.sku
);
